      SUBROUTINE MEDINIT
      IMPLICIT NONE
      COMMON/MEDPARAM/BMIN,BMAX,CENTRMIN,CENTRMAX,BREAL,RAU
      DOUBLE PRECISION BMIN,BMAX,CENTRMIN,CENTRMAX,BREAL,RAU
      COMMON/MEDIUM/MEDIUM
      LOGICAL MEDIUM
      DATA MEDIUM/.FALSE./
      RAU=5.d0
      END


      SUBROUTINE EVENT_GENERATION
      IMPLICIT NONE
      END



      SUBROUTINE MEDNEXTEVT
      IMPLICIT NONE
      END



      SUBROUTINE PICKVTX(X,Y)
      IMPLICIT NONE
      DOUBLE PRECISION X,Y
      X=0.d0
      Y=0.d0
      END



	SUBROUTINE SETB(BVAL)
	IMPLICIT NONE
	DOUBLE PRECISION BVAL
	END



      SUBROUTINE GETSCATTERER(X,Y,Z,T,TYPE,PX,PY,PZ,E,MS,MD,TEMP)
      IMPLICIT NONE
      DOUBLE PRECISION X,Y,Z,T,MS,PX,PY,PZ,E,MD,TEMP
      INTEGER TYPE
      WRITE(*,*)'GETSCATTERER called although in vacuum'
      END



      SUBROUTINE AVSCATCEN(X,Y,Z,T,PX,PY,PZ,E,MS)
      IMPLICIT NONE
      DOUBLE PRECISION X,Y,Z,T,MS,PX,PY,PZ,E
      WRITE(*,*)'AVSCATCEN called although in vacuum'
      END



      SUBROUTINE MAXSCATCEN(PX,PY,PZ,E,MS)
      IMPLICIT NONE
      DOUBLE PRECISION MS,PX,PY,PZ,E
      ms=0.5d0
	e=0.5d0
	px=0.d0
	py=0.d0
	pz=0.d0
      END



      DOUBLE PRECISION FUNCTION GETNEFF(X,Y,Z,T)
      IMPLICIT NONE
      DOUBLE PRECISION X,Y,Z,T
      GETNEFF=0.d0
      END



      DOUBLE PRECISION FUNCTION GETTEMP(X,Y,Z,T)
      IMPLICIT NONE
      DOUBLE PRECISION X,Y,Z,T
      GETTEMP=0.d0
      END


      
      DOUBLE PRECISION FUNCTION GETTEMPMAX()
      IMPLICIT NONE
      GETTEMPMAX=0.d0
      END



      DOUBLE PRECISION FUNCTION GETMDMAX()
      IMPLICIT NONE
      GETMDMAX=0.d0
      END



      DOUBLE PRECISION FUNCTION GETMDMIN()
      IMPLICIT NONE
      GETMDMIN=0.d0
      END



      DOUBLE PRECISION FUNCTION GETMSMAX()
      IMPLICIT NONE
      GETMSMAX=0.d0
      END



      DOUBLE PRECISION FUNCTION GETNEFFMAX()
      IMPLICIT NONE
      GETNEFFMAX=0.d0
      END



	DOUBLE PRECISION FUNCTION GETNATMDMIN()
	IMPLICIT NONE
      GETNATMDMIN=0.d0
	END



      DOUBLE PRECISION FUNCTION GETLTIMEMAX()
      IMPLICIT NONE
	GETLTIMEMAX=0.
	END



      DOUBLE PRECISION FUNCTION GETMD(X,Y,Z,T)
      IMPLICIT NONE
      DOUBLE PRECISION X,Y,Z,T,GETTEMP
      GETMD=0.D0
      END



      DOUBLE PRECISION FUNCTION GETMS(X,Y,Z,T)
      IMPLICIT NONE
      DOUBLE PRECISION X,Y,Z,T,GETMD
      GETMS=0.D0
      END



c      DOUBLE PRECISION FUNCTION MEDDERIV(XVAL,W)
c      MEDDERIV=0.D0
c      END
